 - name: cart Installation
   hosts: all
   become: true
   vars:
     component: cart
     schema: true
   tasks:
     - name: Imported tasks from Nodejs
       ansible.builtin.import_tasks: nodejs.yml
