 - name: Catalogue Installation
   hosts: all
   become: yes
   vars:
     component: catalogue
     scheme: true
   tasks:
     - name: Imported tasks from Nodejs
       ansible.builtin.import_tasks: nodejs.yml
