  - name: Install Dispatch
    hosts: all
    become: true
    component: dispatch
    tasks:
      - name: Copy file
        ansible.builtin.copy:
          src: dispatch.service
          dest: /etc/systemd/system/dispatch.service

      - name: Install the golanguage
        ansible.builtin.yum:
          name: golang
          state: installed

      - name: Application prereq
        ansible.builtin.import_tasks: appprereq.yml

      - name: Start service unit is running
        ansible.builtin.systemd:
          name: dispatch
          daemon_reload: true
          state: restarted
          enabled: yes

