 - name: Copy file
   ansible.builtin.copy:
     src: mongo.conf
     dest: /etc/yum.repos.d/mongo.repo

 - name: Install Mongo
   ansible.builtin.yum:
     name: mongodb-org-shell
     state: installed

 - name: Load Scheme;
   ansible.builtin.shell: host mongodb.ndevops.online </app/schema/"{{component}}".js



