 - name: Copy file
   ansible.builtin.copy:
     src: mongod.conf
     dest: /etc/yum.repos.d/mongo.repo

 - name: Install Mongo
   ansible.builtin.yum:
     name: mongodb-org-shell
     state: installed

 - name: Load Scheme
   ansible.builtin.shell: mongo --host mongodb-dev.ndevops.online </app/schema/{{component}}.js



