 - name: Redis Installation
   hosts: all
   become: true
   tasks:
     - name: Install redis
       ansible.builtin.yum:
         name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
         state: Installed

     - name: Install
       ansible.builtin.shell: yum module enable redis:remi-6.2 -y

     - name: Install
       ansible.builtin.yum:
         name: redis
         state: Installed

     - name: Replace old hostname with new hostname (requires Ansible >= 2.4)
       ansible.builtin.replace:
         path: /etc/redis.conf
         regexp: '127.0.0.1'
         replace: '0.0.0.0'

     - name: Replace old hostname with new hostname (requires Ansible >= 2.4)
       ansible.builtin.replace:
         path: /etc/redis/redis.conf
         regexp: '127.0.0.1'
         replace: '0.0.0.0'

     - name: Redis systemD
       ansible.builtin.systemd:
         name: redis
         state: restarted
         enabled: yes
