 - name: Shipping Installation
   hosts: all
   become: true
   vars:
     component: shipping
     schema: true
   tasks:
     - name: Imported tasks from java
       ansible.builtin.import_tasks: java.yml


