  - name: Copy file
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/{{component}}.service

  - name: Start {{component}} service
    ansible.builtin.systemd:
      name: "{{component}}"
      state: restarted
      enabled: yes
      demon_reload: yes

