 - name: user Installation
   hosts: all
   become: true
   vars:
     component: user
     scheme: true
   tasks:
     - name: Imported tasks from Nodejs
       ansible.builtin.import_tasks: nodejs.yml
